version: "3.1"
name: "nats-playground"
services:
  hub:
    image: nats:2.10.12-alpine3.19
    container_name: "hub"
    ports:
      - 8222:8222
      - 4222:4222
    command:
      - "--config=/etc/nats/nats.conf"
    volumes:
      - ./hub.conf:/etc/nats/nats.conf
    networks:
      - nats

  domain-1:
    image: nats:2.10.12-alpine3.19
    container_name: "domain-1"
    ports:
      - 8223:8222
      - 4223:4222
    command:
      - "--config=/etc/nats/nats.conf"
    volumes:
      - ./leaf.conf:/etc/nats/nats.conf
    depends_on:
      - hub
    networks:
      - nats
 
  domain-2:
    image: nats:2.10.12-alpine3.19
    container_name: "domain-2"
    ports:
      - 8224:8222
      - 4224:4222
    command:
      - "--config=/etc/nats/nats.conf"
    volumes:
      - ./leaf.conf:/etc/nats/nats.conf
    depends_on:
      - hub
    networks:
      - nats

networks:
  nats:
    name: nats
    driver: bridge

